### ISSUE TITLE
node_modules as a source directory

### ISSUE THREAD

**Issue by skodapetr** [linkedpipes/sparqledit#11]
Is there any reason why the libraries are inside node_modules directory?
This directory if often used to hold dependencies described in package.json file, so it seems unusual that the actual code (the interesting part) is located there.

**Comment by martinroucek** [comment]
The reason why all modules are in "node_modules" folder is their requiring/importing. For example, exported classes from library "SparqlAutocompletion" can be imported in module "EditorComponent" this way 
```javascript
import { SparqlLanguageServer } from "SparqlAutocompletion". 
```
This would not work if the modules were not in the "node_modules" folder. Basically, this is one of the ways how to implement multi-repository.

**Comment by martinroucek** [comment]
Sorry, I closed isssue accidentally.

**Comment by skodapetr** [comment]
Ok I see, well then my question would be whether that level of separation is needed. Is there any real potential that some of the project parts will be used outside of this repository?

Alternatively, there are tools that seem to address the design of a monorepository, like [lerna](https://github.com/lerna/lerna) but they also add on a complexity.

It's true that it is more a "personal" preference, could you just for a reference provide a link to a page/best practice that describes/propose the solution that you've used?
