### ISSUE TITLE
Single vs. double quotes

### ISSUE THREAD

**Issue by skodapetr** [linkedpipes/sparqledit#9]
Both are used in the project, sometimes even in a [single file](https://github.com/linkedpipes/sparqledit/blob/master/node_modules/SparqlAutocompletion/test/Autocompletition/SparqlLanguageServerFactoryTest.ts).

Is there any reason for being inconsistent?

Introducing a linter might help with that.

**Comment by martinroucek** [comment]
Fixed in #12
